import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadCustomIcons } from '../custom-icons.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const approved = JSON.parse(await readFile(resolve(root, 'icons/approved.json'), 'utf8'));
const source = await readFile(resolve(root, 'ui/src/components/primitives/icons.generated.ts'), 'utf8');
const colors = JSON.parse(await readFile(resolve(root, 'desktop/assets/colors.json'), 'utf8'));
const nativeTheme = await readFile(resolve(root, 'desktop/src/theme/mod.rs'), 'utf8');
const output = resolve(root, 'desktop/assets');
const check = process.argv.includes('--check');
const notice = 'Iconsax Free artwork, integrated from iconsax@0.1.1; https://docs.iconsax.io/license-and-terms/license. Keep this notice with the generated registry.';
const roles = ['page', 'chrome', 'sidebar', 'surface', 'raised', 'inset', 'hover', 'selected', 'border', 'border_soft', 'text', 'muted', 'subtle', 'accent', 'primary', 'primary_hover', 'on_primary', 'focus', 'success', 'warning', 'danger', 'selection_text'];

for (const mode of ['dark', 'light']) {
    for (const role of roles) {
        const value = colors[mode]?.[role];
        if (!/^#[0-9A-F]{6}$/.test(value ?? '')) throw new Error(`Token contract is missing ${mode}.${role}.`);
        if (!nativeTheme.includes(`${role}: 0x${value.slice(1)}`)) throw new Error(`Native palette is not mapped from ${mode}.${role}.`);
    }
}
if (nativeTheme.includes('ThemeColor::default')) throw new Error('Native semantic colors must not fall back to component defaults.');

const markup = new Map([...source.matchAll(/^\s{4}(?:'([^']+)'|(\w+)):\s*'((?:\\.|[^'])*)',?$/gm)].map(([, quoted, bare, value]) => [quoted ?? bare, value.replaceAll("\\'", "'").replaceAll('\\n', '\n')]));
const customIcons = await loadCustomIcons(approved);
const names = [...Object.keys(approved.icons), ...Object.keys(approved.brandIcons ?? {}), ...customIcons.map(({ name }) => name)];
if (new Set(names).size !== names.length || names.some((name) => !markup.has(name))) throw new Error('Reviewed icon registry and generated UI registry disagree.');
for (const name of Object.keys(approved.icons)) {
    const sourceEntry = approved.icons[name];
    if (typeof sourceEntry === 'object' && !markup.get(name).includes('opacity="0.4"')) throw new Error(`${name} lost its required Iconsax Twotone opacity.`);
}
for (const { name, markup: expected } of customIcons) {
    if (markup.get(name) !== expected) throw new Error(`${name} differs from its approved custom source.`);
}

const files = new Map();
files.set('NOTICE', `${notice}\nOriginal Filebeam custom artwork is listed separately in icons/approved.json and is covered by the repository MIT license.\n`);
files.set('brand/filebeam-mark.svg', await readFile(resolve(root, 'desktop/assets/filebeam-mark.svg'), 'utf8'));
for (const name of names) files.set(`icons/${name}.svg`, `<!-- ${approved.customIcons?.[name]?.description ?? approved.brandIcons?.[name]?.description ?? notice} -->\n<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none">${markup.get(name)}</svg>\n`);
const rust = `// Generated by scripts/desktop/generate-assets.mjs. Do not edit.\n// ${notice}\npub const ICON_NAMES: &[&str] = &[${names.map((name) => JSON.stringify(name)).join(', ')}];\npub const NATIVE_ASSET_PATHS: &[&str] = &[${[...files.keys()].map((path) => JSON.stringify(path)).join(', ')}];\npub fn icon_path(name: &str) -> Option<&'static str> { match name {${names.map((name) => `${JSON.stringify(name)} => Some(${JSON.stringify(`icons/${name}.svg`)}),`).join('')} _ => None } }\npub fn native_asset(path: &str) -> Option<&'static [u8]> { match path {${[...files.keys()].map((path) => `${JSON.stringify(path)} => Some(include_bytes!(${JSON.stringify(`../assets/${path}`)}) as &'static [u8]),`).join('')} _ => None } }\n`;
files.set('native_assets.rs', rust);
for (const [path, contents] of files) {
    const target = resolve(output, path);
    if (check) {
        let current;
        try { current = await readFile(target, 'utf8'); } catch { throw new Error(`${relative(root, target)} is missing; run node scripts/desktop/generate-assets.mjs`); }
        if (current !== contents) throw new Error(`${relative(root, target)} is stale; run node scripts/desktop/generate-assets.mjs`);
    } else { await mkdir(dirname(target), { recursive: true }); await writeFile(target, contents); }
}
