// Generated by scripts/generate-icons.mjs. Do not edit.
// Original Filebeam artwork; not Iconsax artwork.
import SwiftUI

enum ApprovedCustomIcon: String, CaseIterable {
    case httpServer = "http-server"
    case webrtcP2p = "webrtc-p2p"

    var paths: [(Path, Double)] {
        switch self {
        // Original Filebeam artwork: HTTP server transfer; not Iconsax artwork.
        case .httpServer:
            return [
                (Path { path in
                    path.move(to: CGPoint(x: 10, y: 3.5))
                    path.addLine(to: CGPoint(x: 14, y: 3.5))
                    path.addCurve(to: CGPoint(x: 17, y: 6.5), control1: CGPoint(x: 16.4, y: 3.5), control2: CGPoint(x: 17, y: 4.1))
                    path.addLine(to: CGPoint(x: 17, y: 17.5))
                    path.addCurve(to: CGPoint(x: 14, y: 20.5), control1: CGPoint(x: 17, y: 19.9), control2: CGPoint(x: 16.4, y: 20.5))
                    path.addLine(to: CGPoint(x: 10, y: 20.5))
                    path.addCurve(to: CGPoint(x: 7, y: 17.5), control1: CGPoint(x: 7.6, y: 20.5), control2: CGPoint(x: 7, y: 19.9))
                    path.addLine(to: CGPoint(x: 7, y: 6.5))
                    path.addCurve(to: CGPoint(x: 10, y: 3.5), control1: CGPoint(x: 7, y: 4.1), control2: CGPoint(x: 7.6, y: 3.5))
                    path.closeSubpath()
                }, 1),
                (Path { path in
                    path.move(to: CGPoint(x: 7, y: 12))
                    path.addLine(to: CGPoint(x: 17, y: 12))
                    path.move(to: CGPoint(x: 10.5, y: 7.75))
                    path.addLine(to: CGPoint(x: 13.5, y: 7.75))
                    path.move(to: CGPoint(x: 10.5, y: 16.25))
                    path.addLine(to: CGPoint(x: 13.5, y: 16.25))
                    path.move(to: CGPoint(x: 2, y: 19.5))
                    path.addLine(to: CGPoint(x: 2, y: 10.75))
                    path.addCurve(to: CGPoint(x: 4.5, y: 8.25), control1: CGPoint(x: 2, y: 9.09), control2: CGPoint(x: 2.84, y: 8.25))
                    path.addLine(to: CGPoint(x: 5.5, y: 8.25))
                    path.move(to: CGPoint(x: 3.75, y: 6.5))
                    path.addLine(to: CGPoint(x: 5.5, y: 8.25))
                    path.addLine(to: CGPoint(x: 3.75, y: 10))
                    path.move(to: CGPoint(x: 18.5, y: 8.25))
                    path.addCurve(to: CGPoint(x: 20.25, y: 10.75), control1: CGPoint(x: 19.67, y: 8.25), control2: CGPoint(x: 20.25, y: 9.09))
                    path.addLine(to: CGPoint(x: 20.25, y: 19.5))
                    path.move(to: CGPoint(x: 18.5, y: 17.75))
                    path.addLine(to: CGPoint(x: 20.25, y: 19.5))
                    path.addLine(to: CGPoint(x: 22, y: 17.75))
                }, 0.4),
            ]
        // Original Filebeam artwork: WebRTC peer-to-peer transfer; not Iconsax artwork.
        case .webrtcP2p:
            return [
                (Path { path in
                    path.move(to: CGPoint(x: 5, y: 2.5))
                    path.addLine(to: CGPoint(x: 7, y: 2.5))
                    path.addCurve(to: CGPoint(x: 9.5, y: 5), control1: CGPoint(x: 8.88, y: 2.5), control2: CGPoint(x: 9.5, y: 3.12))
                    path.addLine(to: CGPoint(x: 9.5, y: 8))
                    path.addCurve(to: CGPoint(x: 7, y: 10.5), control1: CGPoint(x: 9.5, y: 9.88), control2: CGPoint(x: 8.88, y: 10.5))
                    path.addLine(to: CGPoint(x: 5, y: 10.5))
                    path.addCurve(to: CGPoint(x: 2.5, y: 8), control1: CGPoint(x: 3.12, y: 10.5), control2: CGPoint(x: 2.5, y: 9.88))
                    path.addLine(to: CGPoint(x: 2.5, y: 5))
                    path.addCurve(to: CGPoint(x: 5, y: 2.5), control1: CGPoint(x: 2.5, y: 3.12), control2: CGPoint(x: 3.12, y: 2.5))
                    path.closeSubpath()
                    path.move(to: CGPoint(x: 17, y: 13.5))
                    path.addLine(to: CGPoint(x: 19, y: 13.5))
                    path.addCurve(to: CGPoint(x: 21.5, y: 16), control1: CGPoint(x: 20.88, y: 13.5), control2: CGPoint(x: 21.5, y: 14.12))
                    path.addLine(to: CGPoint(x: 21.5, y: 19))
                    path.addCurve(to: CGPoint(x: 19, y: 21.5), control1: CGPoint(x: 21.5, y: 20.88), control2: CGPoint(x: 20.88, y: 21.5))
                    path.addLine(to: CGPoint(x: 17, y: 21.5))
                    path.addCurve(to: CGPoint(x: 14.5, y: 19), control1: CGPoint(x: 15.12, y: 21.5), control2: CGPoint(x: 14.5, y: 20.88))
                    path.addLine(to: CGPoint(x: 14.5, y: 16))
                    path.addCurve(to: CGPoint(x: 17, y: 13.5), control1: CGPoint(x: 14.5, y: 14.12), control2: CGPoint(x: 15.12, y: 13.5))
                    path.closeSubpath()
                }, 1),
                (Path { path in
                    path.move(to: CGPoint(x: 11.5, y: 6.5))
                    path.addLine(to: CGPoint(x: 16.5, y: 6.5))
                    path.addCurve(to: CGPoint(x: 19, y: 9), control1: CGPoint(x: 18.38, y: 6.5), control2: CGPoint(x: 19, y: 7.12))
                    path.addLine(to: CGPoint(x: 19, y: 11.5))
                    path.move(to: CGPoint(x: 17.25, y: 9.75))
                    path.addLine(to: CGPoint(x: 19, y: 11.5))
                    path.addLine(to: CGPoint(x: 20.75, y: 9.75))
                    path.move(to: CGPoint(x: 12.5, y: 17.5))
                    path.addLine(to: CGPoint(x: 7.5, y: 17.5))
                    path.addCurve(to: CGPoint(x: 5, y: 15), control1: CGPoint(x: 5.62, y: 17.5), control2: CGPoint(x: 5, y: 16.88))
                    path.addLine(to: CGPoint(x: 5, y: 12.5))
                    path.move(to: CGPoint(x: 3.25, y: 14.25))
                    path.addLine(to: CGPoint(x: 5, y: 12.5))
                    path.addLine(to: CGPoint(x: 6.75, y: 14.25))
                    path.move(to: CGPoint(x: 5.5, y: 7.5))
                    path.addLine(to: CGPoint(x: 6.5, y: 7.5))
                    path.move(to: CGPoint(x: 17.5, y: 18.5))
                    path.addLine(to: CGPoint(x: 18.5, y: 18.5))
                }, 0.4),
            ]
        }
    }
}

struct CustomIcon: View {
    let icon: ApprovedCustomIcon
    var size: CGFloat = 20

    var body: some View {
        let paths = icon.paths
        GeometryReader { geometry in
            let scale = min(geometry.size.width, geometry.size.height) / 24
            ZStack {
                ForEach(paths.indices, id: \.self) { index in
                    paths[index].0
                        .applying(CGAffineTransform(scaleX: scale, y: scale))
                        .stroke(style: StrokeStyle(lineWidth: 1.5 * scale, lineCap: .round, lineJoin: .round))
                        .opacity(paths[index].1)
                }
            }
        }
        .frame(width: size, height: size)
        .accessibilityHidden(true)
    }
}
