import { createHash } from 'node:crypto';
import { execFile } from 'node:child_process';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { tmpdir } from 'node:os';
import { promisify } from 'node:util';

const root = new URL('..', import.meta.url);
const outputFiles = [
    new URL('../ui/src/components/primitives/icons.generated.ts', import.meta.url),
    new URL('../backend/app/Support/Icons/Iconsax.php', import.meta.url),
];
const bladeIconDirectory = new URL('../backend/resources/icons/iconsax/', import.meta.url);
const manifest = JSON.parse(await readFile(new URL('../icons/approved.json', import.meta.url), 'utf8'));
const packageLock = JSON.parse(await readFile(new URL('../package-lock.json', import.meta.url), 'utf8'));
const require = createRequire(import.meta.url);
const packageDirectory = dirname(dirname(require.resolve('iconsax')));
const packageJson = join(packageDirectory, 'package.json');
const installedPackage = JSON.parse(await readFile(packageJson, 'utf8'));

if (installedPackage.version !== manifest.source.version) {
    throw new Error(`Expected iconsax ${manifest.source.version}, found ${installedPackage.version}.`);
}
const lockedPackage = packageLock.packages?.['node_modules/iconsax'];
if (lockedPackage?.version !== manifest.source.version || lockedPackage.integrity !== manifest.source.tarballIntegrity) {
    throw new Error('package-lock.json does not pin the approved Iconsax source integrity.');
}

const dataDirectory = join(packageDirectory, 'dist/data');
const catalog = Object.assign(
    {},
    ...(await Promise.all([
        'ai', 'archive', 'arrow', 'astrology', 'building', 'business', 'call', 'car', 'christmas',
        'computers-devices-electronics', 'content-edit', 'crypto', 'cryptocurrency', 'delivery',
        'design-tools', 'emails-messages', 'essential', 'files', 'grid', 'location', 'money',
        'notifications', 'programming', 'school-learning', 'search', 'security', 'settings', 'shop',
        'support-like-question', 'time', 'type-paragraph-character', 'users', 'video-audio-image', 'weather',
    ].map(async (group) => JSON.parse(await readFile(join(dataDirectory, `${group}.json`), 'utf8'))))),
);

function innerSvg(svg) {
    return svg
        .replace(/^<svg\b[^>]*>/, '')
        .replace(/<\/svg>$/, '')
        .replaceAll('white', 'currentColor')
        .replace(/\s+/g, ' ')
        .trim();
}

const entries = Object.entries(manifest.icons).map(([name, source]) => {
    const svg = catalog[source]?.[manifest.source.style];
    if (typeof svg !== 'string') throw new Error(`Missing ${manifest.source.style} source for ${source}.`);
    return [name, innerSvg(svg)];
});
const sourceDigest = createHash('sha256').update(JSON.stringify(entries)).digest('hex');
const notice = `Iconsax Free artwork, integrated from iconsax@${manifest.source.version}; ${manifest.source.licenseUrl}. Keep this notice with the generated registry.`;
const vue = `// Generated by scripts/generate-icons.mjs. Do not edit.\n// ${notice}\nexport const iconNames = ${JSON.stringify(entries.map(([name]) => name), null, 4)} as const;\nexport type IconName = (typeof iconNames)[number];\nexport const iconMarkup: Record<IconName, string> = ${JSON.stringify(Object.fromEntries(entries), null, 4)};\nexport const iconsaxSourceDigest = '${sourceDigest}';\n`;
const php = `<?php\n\ndeclare(strict_types=1);\n\nnamespace App\\Support\\Icons;\n\n/**\n * Generated by scripts/generate-icons.mjs. Do not edit.\n * ${notice}\n */\nfinal class Iconsax\n{\n    public const SOURCE_DIGEST = '${sourceDigest}';\n\n    /** @var array<string, string> */\n    private const MARKUP = ${phpArray(Object.fromEntries(entries))};\n\n    public static function render(string $name, int $size = 20, ?string $label = null): string\n    {\n        if (! isset(self::MARKUP[$name])) {\n            throw new \\InvalidArgumentException(\"Unknown icon: {$name}\");\n        }\n\n        $attributes = $label === null\n            ? 'aria-hidden="true"'\n            : 'role="img" aria-label="'.e($label).'"';\n\n        return '<svg class="fb-icon'.($name === 'loader' ? ' fb-icon--loader' : '').'" width="'.$size.'" height="'.$size.'" viewBox="0 0 24 24" fill="none" '.$attributes.'>'.self::MARKUP[$name].'</svg>';\n    }\n}\n`;

function phpArray(values) {
    return '[\n' + Object.entries(values).map(([name, markup]) => `        '${name}' => '${markup.replaceAll("'", "\\'")}',`).join('\n') + '\n    ]';
}

const run = promisify(execFile);
async function formattedVue(source) {
    const directory = await mkdtemp(join(tmpdir(), 'filebeam-icons-'));
    const file = join(directory, 'icons.generated.ts');
    await writeFile(file, source);
    await run('npx', ['vp', 'fmt', file]);
    const formatted = await readFile(file, 'utf8');
    await rm(directory, { recursive: true, force: true });
    return formatted;
}

const generated = [await formattedVue(vue), php];
const bladeIcons = entries.map(([name, markup]) => [new URL(`${name}.svg`, bladeIconDirectory), `<!-- ${notice} -->\n<svg aria-hidden="true" focusable="false" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">${markup}</svg>\n`]);
if (process.argv.includes('--check')) {
    for (let index = 0; index < outputFiles.length; index += 1) {
        if (await readFile(outputFiles[index], 'utf8') !== generated[index]) {
            throw new Error(`${outputFiles[index].pathname} is stale. Run npm run generate:icons.`);
        }
    }
    for (const [file, source] of bladeIcons) {
        if (await readFile(file, 'utf8') !== source) throw new Error(`${file.pathname} is stale. Run npm run generate:icons.`);
    }
} else {
    await Promise.all(outputFiles.map((file, index) => writeFile(file, generated[index])));
    await Promise.all(bladeIcons.map(([file, source]) => writeFile(file, source)));
}
