<?php

declare(strict_types=1);

use App\Enums\ThemePreset;
use App\Support\Theming\Appearance;
use App\Support\Theming\BrandArtwork;
use App\Support\Theming\Color;
use App\Support\Theming\Palette;
use App\Support\Theming\ThemeDefinition;

require dirname(__DIR__, 2).'/backend/vendor/autoload.php';

if (in_array($argv[1] ?? '', ['--write-default', '--check-default'], true)) {
    $path = dirname(__DIR__, 2).'/backend/resources/themes/default.css';
    $css = "/* Generated by scripts/themes/palette.php --write-default. */\n".(new Palette)->css(fallback: true)."\n";
    if ($argv[1] === '--write-default') {
        file_put_contents($path, $css);
    } elseif (file_get_contents($path) !== $css) {
        fwrite(STDERR, "Default theme CSS is stale. Run php scripts/themes/palette.php --write-default.\n");
        exit(1);
    }
    exit;
}

if (($argv[1] ?? '') === '--write-artwork') {
    foreach (['dark' => 'filebeam-logo-header.svg', 'light' => 'filebeam-logo-header-on-light.svg'] as $mode => $file) {
        file_put_contents(dirname(__DIR__, 2).'/backend/public/brand/'.$file, BrandArtwork::render('logo.svg', new Palette, $mode));
    }
    exit;
}

if (($argv[1] ?? '') === '--contracts') {
    $profiles = [];
    foreach (ThemeDefinition::SEEDS as $preset => $seed) {
        $palette = new Palette($seed);
        foreach (['light', 'dark'] as $mode) {
            $profiles[$preset][$mode] = $palette->tokens($mode);
        }
    }
    echo json_encode(['types' => ThemeDefinition::types(), 'profiles' => $profiles], JSON_THROW_ON_ERROR);
    exit;
}

if (($argv[1] ?? '') === '--asset') {
    $preset = ThemePreset::from($argv[2]);
    $name = $argv[3];
    $source = match ($name) {
        'logo', 'logo-light' => 'logo.svg',
        'mark' => 'mark.svg',
    };
    echo BrandArtwork::render($source, new Palette($preset->primary(Palette::DEFAULT_PRIMARY)), $name === 'logo-light' ? 'light' : 'dark');
    exit;
}

if (($argv[1] ?? '') === '--gallery') {
    $catalog = [];
    foreach (ThemePreset::cases() as $preset) {
        $palette = new Palette($preset->primary(Palette::DEFAULT_PRIMARY));
        $base = '/_theme-preview/'.$preset->value.'/';
        $catalog[] = [
            'id' => $preset->value, 'label' => $preset->label(), 'primary' => $palette->primary,
            'on_color' => Color::contrast('#ffffff', $palette->primary) > Color::contrast('#000000', $palette->primary) ? '#ffffff' : '#000000',
            'branding' => [
                'default_logo_url' => $base.'logo.svg', 'default_light_logo_url' => $base.'logo-light.svg', 'default_mark_url' => $base.'mark.svg',
            ],
            'favicons' => [],
            'chrome' => ['dark' => $palette->tokens()['--fb-browser-chrome'], 'light' => $palette->tokens('light')['--fb-browser-chrome']],
        ];
    }
    echo json_encode([
        'css' => (new Palette)->css().Appearance::stylesheet(),
        'appearance' => [
            'account' => null, 'preference' => ['mode' => 'system', 'preset' => 'instance'],
            'needs_adoption' => false, 'custom_colors' => true, 'catalog' => $catalog,
            'csrf' => null, 'save_url' => '', 'styles_url' => '',
        ],
    ], JSON_HEX_TAG | JSON_HEX_AMP | JSON_THROW_ON_ERROR);
    exit;
}

echo (new Palette($argv[1] ?? Palette::DEFAULT_PRIMARY))->css();
